### ISSUE TITLE
can you update ItemCase for api4?

### ISSUE THREAD

**Issue by UnknownNull** [ItsToxicGG/F#1]

**Comment by ItsToxicGG** [comment]
@UnknownNull sure

**Comment by UnknownNull** [comment]
> @UnknownNull sure

ty. How can I contact you?

**Comment by UnknownNull** [comment]
https://github.com/ItsToxicGG/ItemCase
not work -all bug- you not fixed onRun() and....

[Server thread/INFO]: Enabling NightPVP v1.1
[21:26:46.712] [Server thread/CRITICAL]: ReflectionException: "Class "pocketmime\event\entity\EntityDamageByEntityEvent" does not exist" (-1) in "pmsrc/src/plugin/PluginManager" at line 542
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginManager(542): ReflectionClass->__construct(string[49] pocketmime\event\entity\EntityDamageByEntityEvent)
  #1 pmsrc/src/plugin/PluginManager(564): pocketmine\plugin\PluginManager->getEventsHandledBy(object ReflectionMethod#29803)
  #2 plugins/NightPvP-main/src/Estem01/NightPvP/Main(20): pocketmine\plugin\PluginManager->registerEvents(object Estem01\NightPvP\EventListener#29797, object Estem01\NightPvP\Main#26283)
  #3 pmsrc/src/plugin/PluginBase(117): Estem01\NightPvP\Main->onEnable()
  #4 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object Estem01\NightPvP\Main#26283)
  #6 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#25735)
  #7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[28] E:\minecraft pe server\test\, string[36] E:\minecraft pe server\test\plugins\)
  #8 pmsrc/src/PocketMine(327): pocketmine\server()
  #9 pmsrc(11): require(string[72] phar://E:/minecraft pe server/test/PocketMine-MP.phar/src/PocketMine.php)

**Comment by ItsToxicGG** [comment]
> > @UnknownNull sure
> 
> ty. How can I contact you?

I'm usally on discord
SO u can friend me there and we can chat there
ItsToxicYT#7420
